import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client, S3ServiceException } from '@aws-sdk/client-s3';

/** Object storage for receipts and generated statement files. Keys are generated by the server, never taken from users. */
export interface FileStore {
  readonly kind: 'local' | 's3';
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer | null>;
  delete(key: string): Promise<void>;
}

const SAFE_KEY = /^[A-Za-z0-9][A-Za-z0-9/_.-]{0,300}$/;
export function assertSafeKey(key: string): void {
  if (!SAFE_KEY.test(key) || key.includes('..') || key.includes('//') || key.endsWith('/')) throw new Error(`Unsafe storage key: ${key.slice(0, 40)}`);
}

/** Files on the server's disk. Fine for one server with a persistent, backed-up volume; use S3 for anything else. */
export class LocalDiskStore implements FileStore {
  readonly kind = 'local' as const;
  private root: string;
  constructor(root: string) { this.root = resolve(root); }
  private path(key: string): string {
    assertSafeKey(key);
    const p = resolve(join(this.root, key));
    if (!p.startsWith(this.root + sep)) throw new Error('Storage key escapes the storage root');
    return p;
  }
  async put(key: string, data: Buffer, _contentType?: string): Promise<void> {
    const p = this.path(key);
    await mkdir(dirname(p), { recursive: true });
    await writeFile(p, data, { mode: 0o600 });
  }
  async get(key: string): Promise<Buffer | null> {
    try { return await readFile(this.path(key)); } catch (e) { if ((e as NodeJS.ErrnoException).code === 'ENOENT') return null; throw e; }
  }
  async delete(key: string): Promise<void> { await rm(this.path(key), { force: true }); }
}

export interface S3Options { bucket: string; region: string; endpoint?: string; accessKeyId: string; secretAccessKey: string; forcePathStyle?: boolean; prefix?: string }

/** Any S3-compatible service: AWS S3, Cloudflare R2, Backblaze B2, DigitalOcean Spaces, MinIO. Server-side encryption is left to the bucket policy. */
export class S3Store implements FileStore {
  readonly kind = 's3' as const;
  private client: S3Client; private bucket: string; private prefix: string;
  constructor(o: S3Options) {
    this.bucket = o.bucket; this.prefix = o.prefix ? o.prefix.replace(/\/+$/, '') + '/' : '';
    this.client = new S3Client({
      region: o.region, endpoint: o.endpoint, forcePathStyle: o.forcePathStyle ?? !!o.endpoint,
      credentials: { accessKeyId: o.accessKeyId, secretAccessKey: o.secretAccessKey },
      // Newer SDK defaults add checksum trailers that several S3-compatible services reject.
      requestChecksumCalculation: 'WHEN_REQUIRED', responseChecksumValidation: 'WHEN_REQUIRED',
    });
  }
  private k(key: string) { assertSafeKey(key); return this.prefix + key; }
  async put(key: string, data: Buffer, contentType: string): Promise<void> {
    await this.client.send(new PutObjectCommand({ Bucket: this.bucket, Key: this.k(key), Body: data, ContentType: contentType, ContentLength: data.length }));
  }
  async get(key: string): Promise<Buffer | null> {
    try {
      const r = await this.client.send(new GetObjectCommand({ Bucket: this.bucket, Key: this.k(key) }));
      return Buffer.from(await r.Body!.transformToByteArray());
    } catch (e) {
      if (e instanceof S3ServiceException && (e.name === 'NoSuchKey' || e.$metadata.httpStatusCode === 404)) return null;
      throw e;
    }
  }
  async delete(key: string): Promise<void> { await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: this.k(key) })); }
}

export function createFileStore(env: Record<string, string | undefined>): FileStore {
  const kind = (env.FILE_STORE ?? 'local').toLowerCase();
  if (kind === 'local') return new LocalDiskStore(env.FILE_STORE_DIR || './data/files');
  if (kind === 's3') {
    const need = (k: string) => { const v = env[k]?.trim(); if (!v) throw new Error(`${k} is required when FILE_STORE=s3`); return v; };
    return new S3Store({ bucket: need('S3_BUCKET'), region: env.S3_REGION?.trim() || 'auto', endpoint: env.S3_ENDPOINT?.trim() || undefined,
      accessKeyId: need('S3_ACCESS_KEY_ID'), secretAccessKey: need('S3_SECRET_ACCESS_KEY'),
      forcePathStyle: env.S3_FORCE_PATH_STYLE ? env.S3_FORCE_PATH_STYLE === 'true' : undefined, prefix: env.S3_PREFIX });
  }
  throw new Error(`Unknown FILE_STORE "${kind}" (use local or s3)`);
}
